server:
  port: 9000

spring:
  application:
    name: gateway-service  
  cloud:
    gateway:
      routes:
      - id: authentication-service
        uri: lb://authentication-service
        predicates:
        - Path=/api/v1/auth/** 
      - id: user-service
        uri: lb://user-service
        predicates:
        - Path=/api/v1/user/** 
      - id: customer-service
        uri: lb://customer-service
        predicates:
        - Path=/api/v1/customer/**
      - id: car-service
        uri: lb://car-service
        predicates:
        - Path=/api/v1/car/**


eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    gateway:
      enabled: true
    health:
      group:
        custom:
          include: diskSpace,ping
          show-components: always
          show-details: always
